<a href="https://colab.research.google.com/github/ccherekos-hash/Capstone-Project/blob/main/CapstoneProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import libraries
import pandas as pd
import numpy as np

In [ ]:
# connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# import dataset
df = pd.read_csv('/content/drive/MyDrive/survey_results_public.csv')
df1 = pd.DataFrame(df)
df1

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49118,49119,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49119,49120,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",13.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49120,49121,I am a developer by profession,25-34 years old,"Secondary school (e.g. American high school, G...",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49121,49122,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,None of the above;Engaged in paid work (20-29 ...,10.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
49122,49123,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,10.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0

In [ ]:
# filter by USA
df_usa = df1[df1['Country'] == 'United States of America']
display(df_usa)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
21,22,"I am not primarily a developer, but I write co...",45-54 years old,Some college/university study without earning ...,Employed,None of the above,35.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,interacting with people,NaN,NaN
22,23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0
33,34,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,24.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,business logic,175000.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49063,49064,I am a developer by profession,18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time);Engaged in paid w...,3.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49070,49071,I am learning to code,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,1.0,"Yes, I am not new to coding but am learning ne...",AI CodeGen tools or AI-enabled apps,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49083,49084,"I am not primarily a developer, but I write co...",35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,22.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49084,49085,"I am not primarily a developer, but I write co...",55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Not employed,None of the above,46.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49088,49089,I work with developers or my work supports dev...,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,15.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# remove incomplete data in ConvertedCompYearly
df_usa_cleaned = df_usa.dropna(subset=['ConvertedCompYearly'])
display(df_usa_cleaned)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
22,23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0
33,34,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,24.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,business logic,175000.0,8.0
37,38,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,"I am paid for my knowledge, my knowledge canno...",109000.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48934,48935,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,None of the above,20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,800000.0,8.0
48967,48968,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,9.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools req...",...,OpenRouter;LangChain,NaN,Sentry,NaN,Claude Code;GitHub Copilot;Microsoft Copilot,NaN,When I don’t trust AI’s answers,"Architectural thinking, high level planning",270000.0,8.0
48970,48971,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Communication. I think developers will still b...,350000.0,7.0
48990,48991,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),6.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Stack Overflow or Stack...,"Yes, I learned how to use AI-enabled tools req...",...,Agno;AutoGen (Microsoft);CrewAI;IBM watsonx.ai...,NaN,Adversarial Robustness Toolbox (ART);Langfuse;...,NaN,ChatGPT;GitHub Copilot;Auto-GPT,NaN,When I want to fully understand something;When...,Synthesis - Human applications,167954.0,10.0
49006,49007,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,14.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,Llama Index;LangChain,NaN,Sentry,NaN,ChatGPT;GitHub Copilot;Google Gemini;Cody,NaN,When I want to fully understand something,"problem solving, performing complex tasks acro...",170000.0,7.0

In [ ]:
# filter by employed
df_employed_cleaned = df_usa_cleaned[(df_usa_cleaned['Employment'] == 'Employed')]
df_employed_cleaned.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
22,23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0
33,34,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,24.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,business logic,175000.0,8.0
37,38,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,"I am paid for my knowledge, my knowledge canno...",109000.0,10.0

In [ ]:
# remove extreme outliers
df_employed_cleaned = df_usa_cleaned[
    (df_usa_cleaned['ConvertedCompYearly'] >= 30000) &
    (df_usa_cleaned['ConvertedCompYearly'] <= 500000)
]
display(df_employed_cleaned.head())

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
22,23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0
33,34,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,24.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,business logic,175000.0,8.0
37,38,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,"I am paid for my knowledge, my knowledge canno...",109000.0,10.0

In [ ]:
# filter years coding between 1 and 30 years
df_employed_cleaned = df_employed_cleaned[
    (df_employed_cleaned['YearsCode'] >= 1) &
    (df_employed_cleaned['YearsCode'] <= 30)
]
df_employed_cleaned

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
22,23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0
33,34,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,24.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,business logic,175000.0,8.0
37,38,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,"I am paid for my knowledge, my knowledge canno...",109000.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48930,48931,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,NaN,9.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,Debugging,165000.0,4.0
48967,48968,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,9.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools req...",...,OpenRouter;LangChain,NaN,Sentry,NaN,Claude Code;GitHub Copilot;Microsoft Copilot,NaN,When I don’t trust AI’s answers,"Architectural thinking, high level planning",270000.0,8.0
48970,48971,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Communication. I think developers will still b...,350000.0,7.0
48990,48991,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),6.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Stack Overflow or Stack...,"Yes, I learned how to use AI-enabled tools req...",...,Agno;AutoGen (Microsoft);CrewAI;IBM watsonx.ai...,NaN,Adversarial Robustness Toolbox (ART);Langfuse;...,NaN,ChatGPT;GitHub Copilot;Auto-GPT,NaN,When I want to fully understand something;When...,Synthesis - Human applications,167954.0,10.0
49006,49007,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,14.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,Llama Index;LangChain,NaN,Sentry,NaN,ChatGPT;GitHub Copilot;Google Gemini;Cody,NaN,When I want to fully understand something,"problem solving, performing complex tasks acro...",170000.0,7.0

In [ ]:
import os

# define the directory path
output_dir = '/content/Drive/MyDrive/Colab Notebooks'

# create the directory if it does not exist
os.makedirs(output_dir, exist_ok=True)

# export as CSV to google drive
df_employed_cleaned.to_csv(os.path.join(output_dir, 'survey_USA_cleaned.csv'))

In [ ]:
# create salary quartiles
df_employed_cleaned['SalaryQuartile'] = pd.qcut(
    df_employed_cleaned['ConvertedCompYearly'],
    q=4,
    labels=['Q1 (lowest 25%)', 'Q2 (25%-50%)', 'Q3 (50%-75%)', 'Q4 (top 25%)']
)

# display the count of each quartile
print(df_employed_cleaned['SalaryQuartile'].value_counts().sort_index())
display(df_employed_cleaned.head())

SalaryQuartile
Q1 (lowest 25%)    1006
Q2 (25%-50%)        995
Q3 (50%-75%)       1011
Q4 (top 25%)        990
Name: count, dtype: int64

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat,SalaryQuartile
22,23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0,Q1 (lowest 25%)
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0,Q4 (top 25%)
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0,Q4 (top 25%)
33,34,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,24.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,business logic,175000.0,8.0,Q3 (50%-75%)
37,38,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,Other (please specify):,"I am paid for my knowledge, my knowledge canno...",109000.0,10.0,Q2 (25%-50%)

In [ ]:
import plotly.express as px
#label x and y axis for box plot
fig = px.box(df_employed_cleaned, x='SalaryQuartile', y='ConvertedCompYearly')
fig.update_layout(
    title='Salary Distribution by Quartile in the USA (Employed Developers)',
    xaxis_title='Salary Quartile',
    yaxis_title='Converted Yearly Salary (USD)'
)
# order of the x-axis categories
fig.update_xaxes(
    categoryorder='array',
    categoryarray=['Q1 (lowest 25%)', 'Q2 (25%-50%)', 'Q3 (50%-75%)', 'Q4 (top 25%)']
)
fig.show()

In [ ]:
# create a descriptive statistics table
job_satisfaction_by_quartile = df_employed_cleaned.groupby('SalaryQuartile')['JobSat'].describe()
display(job_satisfaction_by_quartile)

/tmp/ipython-input-2936738304.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

                 count      mean       std  min  25%  50%  75%   max
SalaryQuartile
Q1 (lowest 25%)  708.0  7.019774  2.177331  0.0  6.0  7.0  8.0  10.0
Q2 (25%-50%)     849.0  7.261484  1.999985  0.0  6.0  8.0  9.0  10.0
Q3 (50%-75%)     863.0  7.217845  2.051836  0.0  6.0  8.0  9.0  10.0
Q4 (top 25%)     836.0  7.391148  2.005709  0.0  7.0  8.0  9.0  10.0

In [ ]:
# calculate standard deviation of job satisfaction for each quartile
std_dev = df_employed_cleaned.groupby('SalaryQuartile')['JobSat'].std()
print(std_dev)

SalaryQuartile
Q1 (lowest 25%)    2.177331
Q2 (25%-50%)       1.999985
Q3 (50%-75%)       2.051836
Q4 (top 25%)       2.005709
Name: JobSat, dtype: float64

/tmp/ipython-input-2315647371.py:2: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
# calculate range of job satisfaction for each quartile
range = df_employed_cleaned.groupby('SalaryQuartile')['JobSat'].max() - df_employed_cleaned.groupby('SalaryQuartile')['JobSat'].min()
print(range)

SalaryQuartile
Q1 (lowest 25%)    10.0
Q2 (25%-50%)       10.0
Q3 (50%-75%)       10.0
Q4 (top 25%)       10.0
Name: JobSat, dtype: float64

/tmp/ipython-input-2553893064.py:2: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
# calculate mean for job satisfaction for each quartile
mean = df_employed_cleaned.groupby('SalaryQuartile')['JobSat'].mean()
print(mean)

SalaryQuartile
Q1 (lowest 25%)    7.019774
Q2 (25%-50%)       7.261484
Q3 (50%-75%)       7.217845
Q4 (top 25%)       7.391148
Name: JobSat, dtype: float64

/tmp/ipython-input-3625557105.py:2: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
# test correlation between salary and job satisfaction using numpy basic correlation coefficient
df_correlation = df_employed_cleaned[['ConvertedCompYearly', 'JobSat']].copy()
df_correlation_cleaned = df_correlation.dropna()
print("Cleaned DataFrame for correlation:\n", df_correlation_cleaned.head())

Cleaned DataFrame for correlation:
     ConvertedCompYearly  JobSat
22              87500.0     9.0
29             205000.0     8.0
31             250000.0     8.0
33             175000.0     8.0
37             109000.0    10.0

In [ ]:
correlation_coefficient = df_correlation_cleaned['ConvertedCompYearly'].corr(df_correlation_cleaned['JobSat'])
print(f"Pearson correlation coefficient between ConvertedCompYearly and JobSat: {correlation_coefficient}")

Pearson correlation coefficient between ConvertedCompYearly and JobSat: 0.043723839866245645

In [ ]:
import plotly.express as px

fig = px.scatter(df_correlation_cleaned, x='ConvertedCompYearly', y='JobSat',
                 title='Scatter Plot of Salary vs. Job Satisfaction in the USA')
fig.update_xaxes(title_text='Converted Yearly Salary (USD)')
fig.update_yaxes(title_text='Job Satisfaction (1-15)')
fig.show()

In [ ]:
import plotly.express as px

# prepare the data for the stacked bar chart
satisfaction_by_quartile = df_employed_cleaned.groupby(['SalaryQuartile', 'JobSat'], observed=False).size().reset_index(name='Count')

# create the stacked bar chart
fig = px.bar(satisfaction_by_quartile,
             x='SalaryQuartile',
             y='Count',
             color='JobSat',
             title='Job Satisfaction Levels by Salary Quartile',
             labels={'SalaryQuartile': 'Salary Quartile', 'Count': 'Number of Respondents', 'JobSat': 'Job Satisfaction'})

# ensure the order of SalaryQuartile is correct on the x-axis
fig.update_xaxes(
    categoryorder='array',
    categoryarray=['Q1 (lowest 25%)', 'Q2 (25%-50%)', 'Q3 (50%-75%)', 'Q4 (top 25%)']
)

fig.show()

In [ ]:
# compare satisfaction ratings across quartiles using chi-square test
df_for_contingency = df_employed_cleaned.dropna(subset=['SalaryQuartile', 'JobSat'])
contingency_table = pd.crosstab(df_for_contingency['SalaryQuartile'], df_for_contingency['JobSat'])
display(contingency_table)

JobSat,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0
SalaryQuartile,,,,,,,,,,,
Q1 (lowest 25%),8,5,20,31,27,40,98,153,162,71,93
Q2 (25%-50%),3,6,17,35,22,48,100,176,217,126,99
Q3 (50%-75%),7,8,19,27,23,56,99,178,219,132,95
Q4 (top 25%),7,6,16,22,16,52,85,173,204,152,103

In [ ]:
from scipy.stats import chi2_contingency

chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print(f"Chi-square statistic: {chi2}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:\n", expected)

Chi-square statistic: 41.04442928774323
P-value: 0.08616862486914782
Degrees of freedom: 30
Expected frequencies:
 [[  5.43611794   5.43611794  15.65601966  25.00614251  19.13513514
   42.61916462  83.06388206 147.86240786 174.39066339 104.59090909
   84.8034398 ]
 [  6.51873464   6.51873464  18.77395577  29.98617936  22.94594595
   51.10687961  99.60626536 177.30958231 209.12100737 125.42045455
  101.69226044]
 [  6.6262285    6.6262285   19.08353808  30.48065111  23.32432432
   51.94963145 101.2487715  180.23341523 212.56941032 127.48863636
  103.36916462]
 [  6.41891892   6.41891892  18.48648649  29.52702703  22.59459459
   50.32432432  98.08108108 174.59459459 205.91891892 123.5
  100.13513514]]

In [ ]:
# create a descriptive statistics table
descriptive_stats = df_employed_cleaned.describe()
display(descriptive_stats)

,ResponseId,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,...,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
count,4002.000000,3953.000000,4002.000000,3846.000000,3846.000000,3846.000000,3846.000000,3846.000000,3846.000000,3846.000000,...,3226.000000,3226.000000,3226.000000,3226.000000,3226.000000,3226.000000,3226.000000,3226.000000,4002.000000,3256.000000
mean,21401.579960,12.889704,16.272364,8.458658,3.977119,4.027561,6.004680,3.872855,5.712689,6.665367,...,5.675449,4.395226,4.849969,5.309981,5.858958,4.893986,7.557037,10.171730,157106.171164,7.230651
std,14425.679879,7.946174,7.658924,2.159139,2.219665,2.230716,2.362798,2.355020,2.798175,2.231605,...,2.714600,3.123062,2.610022,2.570556,2.285297,2.500217,2.468531,2.164181,77981.465601,2.057975
min,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30000.000000,0.000000
25%,8481.000000,7.000000,10.000000,8.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,...,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,102000.000000,6.000000
50%,19167.500000,12.000000,15.000000,9.000000,4.000000,4.000000,6.000000,4.000000,6.000000,7.000000,...,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,146164.500000,8.000000
75%,34862.500000,18.000000,22.000000,9.000000,5.000000,5.000000,8.000000,6.000000,8.000000,8.000000,...,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,195000.000000,9.000000
max,49007.000000,61.000000,30.000000,14.000000,13.000000,13.000000,13.000000,14.000000,14.000000,14.000000,...,15.000000,15.000000,15.000000,15.000000,14.000000,14.000000,15.000000,15.000000,500000.000000,10.000000

In [ ]:
# create descriptive statistics table for jobsat, convertedcompyearly, and workexp
descriptive_stats_jobsat = df_employed_cleaned['JobSat'].describe()
descriptive_stats_convertedcompyearly = df_employed_cleaned['ConvertedCompYearly'].describe()
descriptive_stats_workexp = df_employed_cleaned['WorkExp'].describe()
display(descriptive_stats_jobsat)
display(descriptive_stats_convertedcompyearly)
display(descriptive_stats_workexp)

count    3256.000000
mean        7.230651
std         2.057975
min         0.000000
25%         6.000000
50%         8.000000
75%         9.000000
max        10.000000
Name: JobSat, dtype: float64

count      4002.000000
mean     157106.171164
std       77981.465601
min       30000.000000
25%      102000.000000
50%      146164.500000
75%      195000.000000
max      500000.000000
Name: ConvertedCompYearly, dtype: float64

count    3953.000000
mean       12.889704
std         7.946174
min         1.000000
25%         7.000000
50%        12.000000
75%        18.000000
max        61.000000
Name: WorkExp, dtype: float64

In [ ]:
# merge descriptive statistics table for jobsat, convertedcompyearly, and work exp
descriptive_stats_merged = pd.concat([descriptive_stats_jobsat, descriptive_stats_convertedcompyearly, descriptive_stats_workexp], axis=1)
display(descriptive_stats_merged)

            JobSat  ConvertedCompYearly      WorkExp
count  3256.000000          4002.000000  3953.000000
mean      7.230651        157106.171164    12.889704
std       2.057975         77981.465601     7.946174
min       0.000000         30000.000000     1.000000
25%       6.000000        102000.000000     7.000000
50%       8.000000        146164.500000    12.000000
75%       9.000000        195000.000000    18.000000
max      10.000000        500000.000000    61.000000